### ISSUE TITLE
mise use latest does not actually install the latest versions of tools

### ISSUE THREAD

**Issue by nickchomey** [jdx/mise#2275] opened 2024-06-09 18:20 UTC
**Describe the bug**
I just started using mise. When I run `mise use -g go` or `mise use -g go@latest`, it installs 1.22.3, while 1.22.4 is the latest. If I specify `go@1.22.4`, it successfully downloads. Then `mise prune` works to remove 1.22.3, and `mise use -g go` then changes it to `go = "latest"` in confg.toml

The same thing happens with 
* bun - installs 1.1.10 rather than 1.1.12
* deno - 1.44.0 rather than 1.44.1
* python - 3.12.3 rather than 3.12.4

I can update bun to the latest manually and then mise recognizes it as latest (following the same procedure as go). But deno and python just fail. I assume python is because it looks for a standalone build that doesnt yet exist, not sure about deno. 

I'm sure there's a perfectly reasonable explanation for this. But is there something that can be done to resolve it?

**Comment by alock** [comment] 2024-06-09 19:29
I encountered the same issue with the core go plugin.  For me that was the only one I'm using so I just moved away from the core plugin and am using the asdf one with `mise plugins install go https://github.com/asdf-community/asdf-golang`.  Seems like that one doesn't have an issue.

**Comment by mkblast** [comment] 2024-06-10 00:34
Same issue here. also happens when using asdf-zig. can't find 0.13.0 until i specify it.

**Comment by shirayu** [comment] 2024-06-10 13:36
This should be related to #2265

**Comment by jdx** [comment] 2024-06-10 15:15
some jobs are failing, but https://github.com/jdx/mise/issues/2267 is actually the root cause so should be fixed soon

**Comment by jdx** [comment] 2024-06-10 15:31
the repo is private

**Comment by mkblast** [comment] 2024-06-10 22:23
I think the issue if fixed now.

**Comment by roele** [comment] 2024-09-01 10:53
It is possible that this issue has been fixed with [#2512 ](https://github.com/jdx/mise/pull/2512). Mise does cache most requested data like versions, latest version etc which might lead to such behaviour if the cache is not refreshed frequently.

**Comment by BoscoDomingo** [comment] 2024-09-06 15:31
`mise install go@latest` installed 1.23.0 (should've been 1.23.1) and located it in `~/.local/share/mise/installs/go/1.23.0/` instead of the expected `~/.local/share/mise/installs/go/latest/`.

Had to use the [community asdf plugin](https://github.com/asdf-community/asdf-golang) for this to work correctly

**Comment by roele** [comment] 2024-09-06 17:23
@BoscoDomingo Have you disabled the version host requests via `mise set MISE_USE_VERSIONS_HOST=false`? If you want cutting edge versions which were released hours ago you most likely need this setting. I would assume that versions on https://mise-versions.jdx.dev are not updated every hour (as the local cached latest version now is).

**Comment by jdx** [comment] 2024-09-06 22:12
it runs every 6, I could probably change it but I feel like that should be good enough without exploding the git history

**Comment by jdx** [comment] 2024-09-06 22:18
I'm going to close as this was related to the version host failing which is no longer happening. Versions may be up to 30 hours out of date—that is expected and by design. Try `mise cache clear` and `mise set MISE_USE_VERSIONS_HOST=false` if you want to use versions newer than 30 hours at the cost of performance.

**Comment by BoscoDomingo** [comment] 2024-09-07 13:20
It's not so much the version itself (I don't mind running 6 hours behind, really) but the fact it was installed to a specific version's folder instead of `latest`. That would've forced me to update paths every time it is updated, which doesn't happen with any other tool handled by mise

**Comment by jdx** [comment] 2024-09-07 14:00
Did it not create a symlink to latest?

**Comment by BoscoDomingo** [comment] 2024-09-11 13:46
> it should have the same behavior for both:
> 
> ```
> homebrew-core  master ❯ ll ~/.mise/installs/{go,node}
> /Users/jdx/.mise/installs/go:
> lrwxr-xr-x@ - jdx 11 Sep 07:27 1 -> ./1.23.1
> lrwxr-xr-x@ - jdx 11 Sep 07:27 1.23 -> ./1.23.1
> drwxr-xr-x@ - jdx 11 Sep 07:26 1.23.1
> lrwxr-xr-x@ - jdx 11 Sep 07:27 latest -> ./1.23.1
> 
> /Users/jdx/.mise/installs/node:
> lrwxr-xr-x@ - jdx 11 Sep 07:27 22 -> ./22.8.0
> lrwxr-xr-x@ - jdx 11 Sep 07:27 22.8 -> ./22.8.0
> drwxr-xr-x@ - jdx 11 Sep 07:27 22.8.0
> lrwxr-xr-x@ - jdx 11 Sep 07:27 latest -> ./22.8.0
> ```

Yeah that's not what happened for me. I never got a `latest` directory for Go, and both `where go` and `mise where go` would point to the versioned folder despite `mise use -g go@latest` (in fact, `mise where go` still does)

**Comment by jdx** [comment] 2024-09-11 14:30
this looks like a bug with resolving

**Comment by ayZagen** [comment] 2024-09-20 11:34
> Try `mise cache clear` and `mise set MISE_USE_VERSIONS_HOST=false` if you want to use versions newer than 30 hours at the cost of performance.

I wasn't able to try the workaround when I have filed #2548. Today I tried it but it didn't work. mise didn't download Bun `1.1.29`

Using mise `2024.9.6 linux-x64 (1c0bc95 2024-09-18)`

**Comment by jdx** [comment] 2024-11-28 02:38
`mise use *@latest` or `mise install *@latest` should now always use the latest version

**Closed** 2024-12-09 21:54 UTC
Labels: bug
