### ISSUE TITLE
PATH in [env] is paved with good intentions

### ISSUE THREAD

**Issue by pirj** [jdx/mise#2442] opened 2024-08-07 16:45 UTC
### Good intentions

I'm [coming](https://github.com/pirj/dotfiles/commit/1c1c08817914a92d5625bdaa2d3ca8a2bdf50456) from [direnv](https://direnv.net/) that I used for double purpose:
1. Set env vars
2. Set $PATH to include `./bin`.

The latter is extremely useful to save a few keystrokes in Ruby projects by e.g. running `rspec` instead of `bundle exec rspec` after generating [bundler binstubs](https://bundler.io/man/bundle-binstubs.1.html).

direnv provides a [PATH_add](https://direnv.net/man/direnv-stdlib.1.html#codepathadd-ltpathgtcode) in its "stdlib" which [is advertised](https://direnv.net/#the-stdlib) as:
> prepend a path to the $PATH environment variable. Instead of `export PATH=$PWD/bin:$PATH` you can write `PATH_add bin`

I've been adding the `PATH_add ./bin` line to `.envrc` files in every cloned (Ruby-related) repo that had runnable files.

### The road to hell

This served me well, and I tried doing this with `mise`, too.
What I did is I added the following to `.config/mise/config.toml`:
```toml
[env]
PATH = "./bin"
```
And it worked! :tada:
```
$ echo $PATH
./bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:...
```
It actually worked totally as expected and really well in practice.

Until it failed hard when I needed to install a different Ruby version (I'm also coming from [RVM](http://rvm.io/)):
```
$ mise install ruby@3.2
...
env: bash: No such file or directory
mise ~/.cache/mise/ruby/ruby-build/bin/ruby-build exited with non-zero status: exit code 127
```
So I thought maybe the shebang is wrong, and I edited `~/.cache/mise/ruby/ruby-build/bin/ruby-build`:
```diff
- #!/usr/bin/env bash
+ #!/bin/bash
```
after which it could find `bash`, but started failing even harder hinting me towards the culprit:
```
$ mise install ruby@3.2
/Users/pirj/.cache/mise/ruby/ruby-build/bin/ruby-build: line 77: head: command not found
/Users/pirj/.cache/mise/ruby/ruby-build/bin/ruby-build: line 77: ruby-build: command not found
/Users/pirj/.cache/mise/ruby/ruby-build/bin/ruby-build: line 1480: mkdir: command not found
```

### Limbo

No wonder that removing the `PATH = "./bin"` from `.config/mise/config.toml` fixes this. But I need it!

I've tried adding it as:
```toml
PATH = "./bin:$PATH"
```
but it understands it too literally, and doesn't expand the existing env var:
```
$ echo $PATH
./bin:$PATH:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:...
```
That didn't help `mise install` to work.

### Salvation

What would be the idiomatic use of mise-en-place to achieve the desirable effect with no negative side effects?

**Comment by lacostej** [comment] 2024-08-08 15:44
Have you tried `env._.path` (https://mise.jdx.dev/environments.html#env-path)?

**Comment by roele** [comment] 2024-08-09 17:20
I could imagine that the issue might be caused by the "relative" nature of your PATH entry. If your intention is to include the `./bin` directory which is relative to your projects `.mise.toml` file maybe using [templates](https://mise.jdx.dev/templates.html#templates) can help.

```shell
[env]
PATH = "{{config_root}}/bin"
```

**Comment by pirj** [comment] 2024-08-10 09:27
@roele `config_root` practically is the same as the above suggestion of `env._.path`:
> `config_root: PathBuf` – directory containing the `.mise.toml` file

I don't always have a `.mise.toml` file, because some projects have committed `.ruby-version`, which is sufficient.
The majority of the projects don't, though.

Both solutions would be acceptable, but there's a problem.
I have both the global config `~/.config/mise/config.toml` (that specifies this PATH setting) and a project-local (that specifies the Ruby version and serves as an anchor to set the relative path). But both the `config_root` and `env._.path` just add the `bin` which is relative to the global config, not project-local:
```
/Users/pirj/.config/mise/bin:the-rest-of-the-path
```

What seems to set the relative path is:
```
[env]
PATH = "./bin:{{ get_env(name='PATH') }}"
```

However, I've noticed a few glitches.
1. Sometimes it adds it twice:
```
$ echo $PATH
./bin:./bin:/usr/local/opt/openjdk/bin:...
```
2. Instead of the mise-installed `bundler` (`/Users/pirj/.local/share/mise/installs/ruby/3/bin/bundler`), it tries to run the system-provided one (`/usr/bin/bundler`). And I don't get, why, because:
```diff
- /Users/pirj/.local/share/mise/installs/ruby/3/bin:/usr/local/opt/openjdk/bin:...
+ /Users/pirj/.local/share/mise/installs/ruby/3/bin:./bin:./bin:/usr/local/opt/openjdk/bin:...
```
in both cases:
- the mise-installed `bundle` is present in the very first PATH entry (`/Users/pirj/.local/share/mise/installs/ruby/3/bin`)
- `/usr/bin` comes after `/Users/pirj/.local/share/mise/installs/ruby/3/bin`

Also, in the first case the `bundle` is in `./bin`, but it's not considered. 🤔 
This wass confusing, and I failed to make any conclusions to why this may happen.

I was thinking this may be because I failed to provide (a mandatory?) `default` to `get_env`, so I added it:
```
PATH = "./bin:{{ get_env(name='PATH', default='') }}"
```
But that made no difference.

I've also noticed that sometimes `mise` failed to set the Ruby version:
```
$ mise use ruby@3
$ ruby --version
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
```

And it manifested an error with `mise exec` when I tried further debug:
```
$ mise exec ruby@3 -- ruby --version
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: JoinPathsError { inner: JoinPathsError }
Location: src/path_env.rs:50
```
Same even with just `mise exec ruby@3 -- ls`.

With backtrace:
```
$ RUST_BACKTRACE=1 mise exec ruby@3 -- ruby --version
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: JoinPathsError { inner: JoinPathsError }
Location: src/path_env.rs:50

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 9 frames hidden ⋮
  10: <mise::path_env::PathEnv as core::fmt::Display>::fmt::h9a23d9f06b7f19bb
      at <unknown source file>:<unknown line>
  11: mise::toolset::Toolset::env_with_path::he2ff17aa719d9335
      at <unknown source file>:<unknown line>
  12: mise::cli::exec::Exec::run::hd2f0de645d55532e
      at <unknown source file>:<unknown line>
  13: mise::cli::Cli::run::h5f9fbe3e025347e9
      at <unknown source file>:<unknown line>
  14: mise::main::hca6cf4f9cac5a769
      at <unknown source file>:<unknown line>
  15: std::sys_common::backtrace::__rust_begin_short_backtrace::hd8ce35e5ba306c91
      at <unknown source file>:<unknown line>
  16: std::rt::lang_start::{{closure}}::ha5bae569b024d6e2
      at <unknown source file>:<unknown line>
  17: std::panicking::try::hbd0fe5c14227076d
      at <unknown source file>:<unknown line>
  18: std::rt::lang_start_internal::h05ec03c5e90cb659
      at <unknown source file>:<unknown line>
  19: _main<unknown>
      at <unknown source file>:<unknown line>
```

Am I doing something wrong?

**Comment by mcallaway** [comment] 2024-08-28 01:38
The JoinPathsError may have been fixed in [v2024.8.14](https://github.com/jdx/mise/releases/tag/v2024.8.14).

**Comment by pirj** [comment] 2024-08-28 07:44
The problem is fixed, thanks to everyone involved 🎉 

That works:
```
[env]
PATH = "./bin:{{ get_env(name='PATH') }}"
```

The following won't work because it assumes the `bin/` to be in config_root, which is typically `~/.config/mise`:
```
[env]
_.path = [
  "./bin"
]
```
```
[env]
PATH = "{{config_root}}/bin"
```

The following won't work, but it probably shouldn't as it looks like an override, not like a join:
```
[env]
PATH = "./bin"
```

I'm willing to add documentation if you think this case is worth documenting.

**Comment by pirj** [comment] 2024-08-28 17:39
Adding the `./bin` to the PATH worked. I even found [a simpler way](https://mise.jdx.dev/environments.html#using-env-vars-in-other-env-vars) of configuring this in the documentation:
```
[env]
PATH = "./bin:{{ env.PATH }}"
```

However, this has two negative side effects:
1. Setting the right version
2. The $PATH grows exponentially

The following two snippet demonstrates the problem.
1. How it should be (without the `env.PATH` trick). When entering a directory with some configuration in `.mise.toml`, mise prepends the PATH with `/Users/pirj/.local/share/mise/installs/ruby/3.3/bin`, and removes it when leaving the directory:
```
$ echo $PATH
/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin
$ j core
$ echo $PATH
/Users/pirj/.local/share/mise/installs/ruby/3.3/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin
$ cd
$ echo $PATH
/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin
```

2. Faulty, with the `env.PATH` trick. When entering a directory with some configuration in `.mise.toml`, mise not only prepends the PATH with `/Users/pirj/.local/share/mise/installs/ruby/3.3/bin` and `.bin`, but somehow doubles the contents of $PATH. It does not remove the added paths when leaving the directory, too:
```
$ echo $PATH
./bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin
$ j core
$ echo $PATH
./bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/Users/pirj/.local/share/mise/installs/ruby/3.3/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin
$ cd
$ echo $PATH
./bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin:/usr/local/sbin:/Users/pirj/.bin:/Users/pirj/go/bin
```

The problem is more evident on the screenshot:
| Normal | Doubled, not cleaned on leave |
| --- | --- |
| <img width="268" alt="image" src="https://github.com/user-attachments/assets/3dc47194-3a2f-418a-860f-d88677beb3e3"> | <img width="343" alt="image" src="https://github.com/user-attachments/assets/173feb5c-5aec-4ce5-bce2-67a42c4e133e"> |

The `./bin` is indeed in the path, but the `/Users/pirj/.local/share/mise/installs/ruby/3.3/bin` is buried so deep that the system installed (or Homebrew-installed) Ruby takes precedence.

It seems that the PATH joining misbehaves in the presence of `env.PATH = `, what do you think @mcallaway ?

**Comment by jdx** [comment] 2024-08-28 22:23
I believe we should make this function as you expect:

```toml
[env]
_.path = [
  "./bin"
]
```

the reason it doesn't is because the assumption is that in general mise assumes it's configuring a specific project so the fact that "." is related to the file's directory is not a bug, but there should be a way to effectively do `$PWD/bin`.

**Comment by jdx** [comment] 2024-11-28 01:45
this appears to be working mostly when doing the following:

```toml
[env]
_.path = ["{{cwd}}/bin"]
```

however https://github.com/jdx/mise/pull/3258 needs to land because right now `hook-env` doesn't run if only the directory changes

**Closed** 2024-11-28 02:22 UTC
Labels: enhancement

**Comment by 13k** [comment] 2025-02-10 04:16
I belive this is still an issue for yet another edge case: when different tools provide binaries with the same name.

The root cause is still mise appending to PATH instead of prepending.

This happens for `lua` and `luajit`:

```console
❱ ls -T
.
├── child
│   └── mise.toml
└── mise.toml
```

```toml
# $root/mise.toml
[tools]
lua = "5.4.7"
```

```toml
# $root/child/mise.toml
[tools]
luajit = "2.1.0-beta3"
```

```console
❱ cd "$root"
❱ type -ap luarocks
~/.local/share/mise/installs/lua/5.4.7/luarocks/bin/luarocks
❱ mise doctor path
~/.local/share/mise/installs/lua/5.4.7/bin
~/.local/share/mise/installs/lua/5.4.7/luarocks/bin

❱ cd "child"
❱ type -ap luarocks
~/.local/share/mise/installs/lua/5.4.7/luarocks/bin/luarocks
~/.local/share/mise/installs/luajit/2.1.0-beta3/bin/luarocks
❱ mise doctor path
~/.local/share/mise/installs/lua/5.4.7/bin
~/.local/share/mise/installs/lua/5.4.7/luarocks/bin
~/.local/share/mise/installs/luajit/2.1.0-beta3/bin
```

This would almost never happen with two different tools, assuming they don't provide the same executables (which is a risk-taking assumption), but in the case of `lua` and `luajit`, they are semantically the same tool, but have different names.

I don't believe the issue to be different tools providing the same binaries, though. Prepending to PATH should solve all of that without the need to special case any tool.
