### ISSUE TITLE
Answering "yes" to paranoid trust prompts doesn't persist

### ISSUE THREAD

**Issue by notpeelz** [jdx/mise#1972] opened 2024-04-27 16:37 UTC
**To Reproduce**
1. `printf '[settings]\nparanoid = true' > ~/.config/mise/config.toml`
2. `rm -rf ~/.local/state/mise`
3. `mise ls` (answer "Yes" to trust prompt)
4. `echo >> ~/.config/mise/config.toml`
5. `mise ls` (answer "Yes" to trust prompt)
6. `mise ls` and see the trust prompt again
 
**`mise doctor` output**

```
version: 2024.4.8 linux-x64 (d04339c 2024-04-23)
activated: no
shims_on_path: yes

build_info: 
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Tue, 23 Apr 2024 01:16:13 +0000
  Rust Version: rustc 1.77.2 (25ef9e3d8 2024-04-09)
  Profile: release

shell: 
  /usr/bin/zsh
  zsh 5.9 (x86_64-pc-linux-gnu)

dirs: 
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/.cache/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files: 
  ~/.config/mise/config.toml

plugins: 
  bun     (core)
  deno    (core)
  go      (core)
  java    (core)
  node    (core)
  python  (core)
  ruby    (core)
  rust    https://github.com/code-lever/asdf-rust.git#95acf4f
  usage   https://github.com/jdx/mise-usage.git#fe3888a

toolset: 


env_vars: 
  (none)

settings: 
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = false
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  node_compile = false
  not_found_auto_install = true
  paranoid = true
  plugin_autoupdate_last_check_duration = "7d"
  python_compile = false
  python_default_packages_file = "/home/peelz/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  yes = false
  ci = false
  debug = false
  trace = false
  log_level = "info"
  python_venv_auto_create = false

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false

No warnings found
No problems found
```

**Comment by roele** [comment] 2024-04-28 11:37
This might be a duplicate of #1746

**Closed** 2024-04-28 13:46 UTC
Labels: bug
