### ISSUE TITLE
mise use altering global config if local config does not exist

### ISSUE THREAD

**Issue by silverhikari** [jdx/mise#2259] opened 2024-06-06 05:50 UTC
**Describe the bug**
 if using `mise use language@version`(tested this with different languages and version but still alters the global) and if a local .mise.toml does not exist, it will alter the global mise config even if -g or --global is not specified. this bug will not happen if a pre-existing or manually created .mise.toml exists in the directory.

**To Reproduce**
1. check global version used by mise 
2. go to empty directory or a project without .mise.toml
3.  `mise use language@version`

**Expected behavior**
if `mise use language@version` is used in a directory without a .mise.toml it will be created and set to use the version specified in the command.

**`mise doctor` output**

```
version: 2024.6.1 linux-x64 (44b2ef6 2024-06-05)
activated: yes
shims_on_path: no

build_info: 
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS
  Built: Wed, 5 Jun 2024 04:23:07 +0000
  Rust Version: rustc 1.78.0 (9b00956e5 2024-04-29)
  Profile: release

shell: 
  /bin/bash
  GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu)
  Copyright (C) 2022 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

dirs: 
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/.cache/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files: 
  ~/.config/mise/config.toml
  ~/mise-test/.mise.toml

backends: 
  cargo
  core
  go
  npm
  pipx
  spm
  ubi

plugins: 
  bun     (core)
  deno    (core)
  erlang  (core)
  go      (core)
  java    (core)
  nim     https://github.com/asdf-community/asdf-nim#397c14a
  node    (core)
  python  (core)
  ruby    (core)

toolset: 
  node@18.20.2  
  ruby@3.1.4    
  nim@2.0.4     

env_vars: 
  MISE_SHELL=bash

settings: 
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = false
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  http_timeout = 30
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  node_compile = false
  not_found_auto_install = true
  paranoid = false
  plugin_autoupdate_last_check_duration = "7d"
  python_default_packages_file = "/home/silver/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  yes = false
  ci = false
  debug = false
  trace = false
  log_level = "info"
  python_venv_auto_create = false

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false

No warnings found
No problems found
```

**Additional context**
Add any other context about the problem here. Consider running mise with `--debug` or `--trace` for extra debug info.

**Comment by hinricht** [comment] 2024-06-07 09:50
Duplicate of #2256 ?

**Closed** 2024-06-07 15:05 UTC
Labels: bug
