### ISSUE TITLE
Hooks don't seem to work

### ISSUE THREAD

**Issue by vrslev** [jdx/mise#3283] opened 2024-11-29 09:09 UTC
**Describe the bug**
They fail with "No such file or directory"

**To Reproduce**
Steps to reproduce the behavior.

Activate mise on fish, zsh or bash, then:

```sh
cd /tmp && mkdir t && cd t && echo "hooks.cd = \"echo 'executed cd hook'\"">mise.toml && mise trust && cd .. && cd t
```

You'll see the output:

```
mise WARN  No untrusted config files found.
error: Error reading script file 'echo 'executed cd hook'':
error: No such file or directory
mise WARN  error executing hook: command ["fish", "echo \'executed cd hook\'"] exited with code 127
```

**Expected behavior**
Hooks work :)

**`mise doctor` output**

```text
version: 2024.11.34 macos-arm64 (90f5798 2024-11-29)
activated: yes
shims_on_path: no

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Fri, 29 Nov 2024 07:08:52 +0000
  Rust Version: rustc 1.82.0 (f6e511eec 2024-10-15)
  Profile: release

shell:
  /opt/homebrew/bin/fish
  fish, version 3.7.1

dirs:
  cache: ~/Library/Caches/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.toml
  ~/.config/mise/config.local.toml
  ~/code/dotfiles/mise.toml

backends:
  aqua
  asdf
  cargo
  core
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:
  aqua:BurntSushi/ripgrep@14.1.1
  aqua:koalaman/shellcheck@0.10.0
  cargo:mergiraf@0.3.1
  core:bun@1.1.37
  core:go@1.23.3
  core:node@23.3.0
  core:python@3.10.15
  core:python@3.11.10
  core:python@3.12.7
  core:python@3.13.0
  core:rust@1.83.0
  pipx:cookiecutter@2.6.0
  pipx:glances@4.2.1
  pipx:maturin@1.7.6
  pipx:poetry@1.8.4
  pipx:pre-commit@4.0.1
  pipx:python-lsp-server@1.12.0
  pipx:sqlfluff@3.2.5
  spm:sindresorhus/macos-trash@v1.2.0
  ubi:XAMPPRocky/tokei@12.1.2
  ubi:ajeetdsouza/zoxide@0.9.6
  ubi:cargo-bins/cargo-binstall[tag_regex=^\d\.]@1.10.14
  ubi:casey/just@1.37.0
  ubi:cli/cli[exe=gh]@2.63.0
  ubi:dandavison/delta@0.18.2
  ubi:ducaale/xh@0.23.0
  ubi:gohugoio/hugo@0.139.2
  ubi:hadolint/hadolint@2.12.0
  ubi:helmfile/helmfile@0.169.1
  ubi:jdx/usage@1.3.3
  ubi:jkfran/killport@1.1.0
  ubi:junegunn/fzf@0.56.3
  ubi:mikefarah/yq@4.44.5
  ubi:mitsuhiko/insta@1.41.1
  ubi:pvolok/mprocs@0.7.1
  ubi:sharkdp/bat@0.24.0
  ubi:sharkdp/fd@10.2.0
  ubi:sharkdp/hyperfine@1.19.0
  ubi:starship/starship@1.21.1

env_vars:
  MISE_SHELL=fish

settings:
  experimental          true                                                                                                                                                           ~/.config/mise/config.toml
  jobs                  8                                                                                                                                                              ~/.config/mise/config.toml
  pipx.uvx              true                                                                                                                                                           ~/.config/mise/config.toml
  python.uv_venv_auto   true                                                                                                                                                           ~/.config/mise/config.toml
  trusted_config_paths  ["~/.config/mise/config.local.toml", "~/.config/mise/config.toml", "~/code/dotfiles/config/mise/config.local.toml", "~/code/dotfiles/config/mise/config.toml"] ~/.config/mise/config.toml

No problems found

```

**Additional context**
Nope.

**Comment by jdx** [comment] 2024-11-29 09:15
this is a duplicate of https://github.com/jdx/mise/issues/3280

**Closed by jdx** 2024-11-29 09:15 UTC
Labels: bug
