### ISSUE TITLE
protoc plugin install error

### ISSUE THREAD

**Issue by sedubois** [jdx/mise#2287] opened 2024-06-14 12:09 UTC
**Describe the bug**
Error when installing the protoc community plugin.

**To Reproduce**
```
$ mise plugin install protoc
mise ⚠️ protoc is a community-developed plugin – https://github.com/paxosglobal/asdf-protoc
Would you like to install protoc? Yes
mise plugin:protoc cloning https://github.com/paxosglobal/asdf-protoc.git
smunmap_chunk(): invalid pointer
Aborted (core dumped)
```

**Expected behavior**
Plugin installs fine, like it does with asdf on the same machine.

**`mise doctor` output**

```text
$ mise doctor
version: 2024.6.3 linux-arm64 (f01cc8d 2024-06-10)
activated: yes
shims_on_path: no

build_info: 
  Target: aarch64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Mon, 10 Jun 2024 15:39:56 +0000
  Rust Version: rustc 1.78.0 (9b00956e5 2024-04-29)
  Profile: release

shell: 
  /bin/bash
  GNU bash, version 5.1.16(1)-release (aarch64-unknown-linux-gnu)
  Copyright (C) 2020 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

dirs: 
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/.cache/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files: 
  ~/.config/mise/config.toml
  ~/Documents/mise-demo/.tool-versions

backends: 
  cargo
  core
  go
  npm
  pipx
  spm
  ubi
free(): invalid next size (fast)
Aborted (core dumped)
```

**Additional context**

```
$ mise plugin install protoc --debug --force
[DEBUG] ARGS: /home/parallels/.local/bin/mise plugin install protoc --debug --force
[DEBUG] Config {
    Config Files: [
        "~/Documents/mise-demo/.tool-versions",
        "~/.config/mise/config.toml",
    ],
}
[DEBUG] install protoc "https://github.com/paxosglobal/asdf-protoc.git"
uninstalling
removing ~/.local/share/mise/plugins/protoc
cloning https://github.com/paxosglobal/asdf-protoc.git
[DEBUG] cloning https://github.com/paxosglobal/asdf-protoc.git to /home/parallels/.local/share/mise/plugins/protoc
free(): invalid next size (fast)
Aborted (core dumped)
```

The operating system is Ubuntu 22.04.2 LTS, running in Parallels VM with x86_64 emulation on a mac with Apple Silicon chip.

`asdf plugin add protoc` and `asdf install` did not yield errors on the same machine.

Here is the relevant entry in `.tool-versions`:
```
protoc 25.3
```

**Comment by roele** [comment] 2024-06-14 15:56
I am unable to reproduce this neither on macOS nor on the Linux (aarch64)  Dev Container but it seems to occur if i use a minimal Ubuntu Docker image. I assume this is caused by a missing library.

**Comment by jdx** [comment] 2024-06-14 17:13
there was a similar issue around something involving page size

**Comment by roele** [comment] 2024-06-15 05:21
I assume you're referring to #2196?

**Comment by roele** [comment] 2024-06-15 08:35
The [git2 crate](https://crates.io/crates/git2) states that it has a dependency on `libgit2`.

Installing `libgit2-1.7` on my Ubuntu 24.04 Docker image does resolve the issue.
```bash
apt-get install libgit2-1.7
```

**Comment by jdx** [comment] 2024-06-15 11:35
I'm on board but maybe just for precompiled mise like we do for OpenSSL.

**Comment by roele** [comment] 2024-06-16 18:45
As mentioned in [git2 crate](https://crates.io/crates/git2) some systems still require the system version of libgit2. Setting the environment variable `LIBGIT2_NO_VENDOR=1` resolves the issue in this case.

**Comment by chadlwilson** [comment] 2024-07-03 14:02
> As mentioned in [git2 crate](https://crates.io/crates/git2) some systems still require the system version of libgit2 even with vendored libgit2 . Setting the environment variable `LIBGIT2_NO_VENDOR=1` resolves the issue in this case.

I'm not sure I understand what you are talking about here, but on Ubuntu 24.04 `apt-get install libgit2-1.7` with or without `LIBGIT2_NO_VENDOR=1` on a `mise use` didn't help stop it crashing.

```shell
docker run -t ubuntu:24.04 bash -c 'apt-get update && apt-get -y install curl libgit2-1.7 && (curl https://mise.jdx.dev/install.sh | sh) && LIBGIT2_NO_VENDOR=1 /root/.local/bin/mise use --global --debug -vv ruby@3.3.3'
```

**Comment by jdx** [comment] 2024-07-03 14:05
I suggest `cargo install mise` as a workaround

**Comment by chadlwilson** [comment] 2024-07-03 14:11
> I suggest `cargo install mise` as a workaround

`error: cannot install package `mise 2024.6.6`, it requires rustc 1.76.0 or newer, while the currently active rustc version is 1.75.0`

Additionally, I don't really want to install a 668MB toolchain (estimate from just adding `cargo`) while trying to use mise within a container to install other tools.

Will go back to an earlier version for now.

**Comment by jdx** [comment] 2024-07-03 17:03
maybe we'd have better luck with [gitoxide](https://crates.io/crates/gitoxide)

**Comment by roele** [comment] 2024-07-07 14:23
There is a newer version of git2 available (see https://github.com/jdx/mise/pull/2300) which bumps to `libgit2-sys-1.8.1` which might or might not address some issues. Unfortunately the dependency on `built` also using git2 currently prevents us from updating. I prepared a PR to bump the git2 version in built at https://github.com/lukaslueg/built/pull/69.

**Comment by roele** [comment] 2024-07-07 18:27
I also had a quick look at `gitoxide` but is seems it's far from feature complete and checkouts of specific revisions as used by SPM (Swift Package Manager) backend for example are not supported yet.

**Comment by roele** [comment] 2024-07-08 16:49
@chadlwilson If you have a way to verify, i would be interested to know if the issue still occurs with version 2024.7.1 (now that https://github.com/jdx/mise/pull/2357 is merged).

I personally run a couple manual tests on a Debian Docker container and did not encounter it anymore.

**Comment by chadlwilson** [comment] 2024-07-08 17:54
Thanks @roele - this seems to have done the trick!

https://github.com/gocd-contrib/gocd-oss-cookbooks/actions/runs/9844334610/job/27177733650 (this is building an arm64 CrntOS Stream 9 image with mise installed on a native arm64 Linux GHA runner - failing due to an unrelated Node issue but not crashing now)

**Comment by chadlwilson** [comment] 2024-07-09 01:30
I also cannot replicate anything via arm64 containers on my Apple Silicon machine with `2024.7.1`, which I could 95% reliably replicate before, so I think it's reasonably safe to say this has nailed both this and #2196 ?

**Closed** 2024-07-17 03:11 UTC
Labels: bug
