### ISSUE TITLE
registry: ripgrep not actually gets installed

### ISSUE THREAD

**Issue by vrslev** [jdx/mise#3196] opened 2024-11-25 07:57 UTC
**Describe the bug**
There's some issue with ripgrep in registry: it doesn't get installed

**To Reproduce**
```sh
cd /tmp && mkdir t && cd t
mise use ripgrep
mise x ripgrep -- rg
```

**Expected behavior**
Expected to install ripgrep. Now it outputs this:

```
mise ERROR "rg" couldn't exec process: No such file or directory
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

**`mise doctor` output**

```text
version: 2024.11.29 macos-arm64 (644cb6d 2024-11-25)
activated: yes
shims_on_path: no

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Mon, 25 Nov 2024 04:15:52 +0000
  Rust Version: rustc 1.82.0 (f6e511eec 2024-10-15)
  Profile: release

shell:
  /opt/homebrew/bin/fish
  fish, version 3.7.1

dirs:
  cache: ~/Library/Caches/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.local.toml
  ~/.config/mise/config.toml
  /private/tmp/t/mise.toml

backends:
  aqua
  asdf
  cargo
  core
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:
  aqua:BurntSushi/ripgrep@14.1.1
  aqua:cargo-bins/cargo-binstall@1.10.14
  aqua:cli/cli@2.62.0
  cargo:mergiraf@0.3.1
  core:bun@1.1.36
  core:go@1.23.3
  core:node@23.3.0
  core:python@3.10.15
  core:python@3.11.10
  core:python@3.12.7
  core:python@3.13.0
  pipx:cookiecutter@2.6.0
  pipx:glances@4.2.1
  pipx:maturin@1.7.4
  pipx:poetry@1.8.4
  pipx:pre-commit@4.0.1
  pipx:python-lsp-server@1.12.0
  pipx:sqlfluff@3.2.5
  spm:sindresorhus/macos-trash@v1.2.0
  ubi:XAMPPRocky/tokei@12.1.2
  ubi:ajeetdsouza/zoxide@0.9.6
  ubi:casey/just@1.37.0
  ubi:dandavison/delta@0.18.2
  ubi:ducaale/xh@0.23.0
  ubi:gohugoio/hugo@0.139.2
  ubi:hadolint/hadolint@2.12.0
  ubi:helmfile/helmfile@0.169.1
  ubi:jdx/usage@1.3.3
  ubi:jkfran/killport@1.1.0
  ubi:junegunn/fzf@0.56.3
  ubi:koalaman/shellcheck@0.10.0
  ubi:mikefarah/yq@4.44.5
  ubi:mitsuhiko/insta@1.41.1
  ubi:pvolok/mprocs@0.7.1
  ubi:sharkdp/bat@0.24.0
  ubi:sharkdp/fd@10.2.0
  ubi:sharkdp/hyperfine@1.19.0
  ubi:starship/starship@1.21.1

env_vars:
  MISE_SHELL=fish

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cache_prune_age = "30d"
  ci = false
  color = true
  debug = false
  disable_backends = []
  disable_default_registry = false
  disable_hints = []
  disable_tools = []
  exec_auto_install = true
  experimental = true
  fetch_remote_versions_cache = "1h"
  fetch_remote_versions_timeout = "10s"
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  http_timeout = "30s"
  ignored_config_paths = []
  jobs = 8
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  libgit2 = true
  lockfile = true
  log_level = "info"
  not_found_auto_install = true
  paranoid = false
  pin = false
  pipx_uvx = true
  plugin_autoupdate_last_check_duration = "7d"
  quiet = false
  raw = false
  task_run_auto_install = true
  task_skip = []
  trace = false
  trusted_config_paths = [
      "~/.config/mise/config.local.toml",
      "~/.config/mise/config.toml",
      "~/code/dotfiles/config/mise/config.local.toml",
      "~/code/dotfiles/config/mise/config.toml",
  ]
  unix_default_file_shell_args = ["sh"]
  unix_default_inline_shell_args = [
      "sh",
      "-c",
  ]
  use_file_shell_for_executable_tasks = false
  use_versions_host = true
  verbose = false
  windows_default_file_shell_args = [
      "cmd",
      "/c",
  ]
  windows_default_inline_shell_args = [
      "cmd",
      "/c",
  ]
  windows_executable_extensions = [
      "exe",
      "bat",
      "cmd",
      "com",
      "ps1",
      "vbs",
  ]
  yes = false

  [aqua]
  cosign = true
  slsa = true

  [cargo]
  binstall = true

  [node]

  [npm]
  bun = false

  [pipx]
  uvx = true

  [python]
  default_packages_file = "~/.default-python-packages"
  pyenv_repo = "https://github.com/pyenv/pyenv.git"
  venv_auto_create = false
  venv_stdlib = false

  [ruby]
  default_packages_file = "~/.default-gems"
  ruby_build_repo = "https://github.com/rbenv/ruby-build.git"
  ruby_install = false
  ruby_install_repo = "https://github.com/postmodern/ruby-install.git"

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false

No problems found
```

(really nice that I didn't have to strip sensitive data from `mise doctor` output 👍)

**Additional context**
Nope :)

**Comment by rhysm94** [comment] 2024-11-25 11:08
I had exactly the same issue with a different tool.
After `mise x -- tuist` and `mise x -- sourcery` failing on me, I tried explicitly calling `mise use tuist` which informed me that `.mise.toml` wasn't trusted, and I could trust it with `mise trust` in the directory.
Since doing that, `mise x -- tuist` and `mise x -- sourcery` are working again, thankfully!

**Comment by jdx** [comment] 2024-11-25 11:27
I don't think that's the case here since it's showing up in `mise dr` as a config file. Is there an empty install? What's in `~/.local/share/mise/installs/ripgrep/latest`?

**Comment by jdx** [comment] 2024-11-25 11:30
I can't seem to reproduce this. I tried ctrl-c'ing during the install and every time it doesn't show up as an install if it only partially completes as it should.

**Comment by rhysm94** [comment] 2024-11-25 14:50
@jdx I think the issue isn't what OP @vrslev initially thought, but is actually due to changes around trusting `.mise.toml` files. I had the exact same error message, and it was resolved by running `mise trust` in the directory which, as of Friday, was working OK.

**Comment by vrslev** [comment] 2024-11-25 15:42
> I don't think that's the case here since it's showing up in `mise dr` as a config file. Is there an empty install? What's in `~/.local/share/mise/installs/ripgrep/latest`?

It's contains an empty `bin` folder

**Comment by jdx** [comment] 2024-11-25 15:48
I'm not sure how that happened but does it occur if you reinstall?

**Closed** 2024-11-26 13:40 UTC
Labels: bug
